name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: [Deploy to Docker Hub]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create deploy file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: deploy.yml.j2
          output_file: deploy.yml
          strict: true
          variables: |
            commit_sha=${{ github.sha }}

      - name: Downcase repo name
        id: downcase-repo-name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.name }}

      - name: Copy file on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_KEY }}
          source: deploy.yml
          target: /home/ubuntu/deploy/${{ steps.downcase-repo-name.outputs.lowercase }}/deploy.yml

      - name: Execute kubectl on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_KEY }}
          script: |
            kubectl apply -f /home/ubuntu/deploy/${{ steps.downcase-repo-name.outputs.lowercase }}/deploy.yml
